### ISSUE TITLE
Add an option to filter results by time

### ISSUE THREAD

**Issue by jac08h** [FelixVanOost/Strava-Analysis-Tool#67]
Add an option to select timeframe of the results, e.g. last month, last 3 weeks, April 2019 - September 2019.
This timeframe would then be used to output summary and graphs. 

As the dates are already stored in pandas dataframe, filtering them by date should be possible. I'm not sure where the user would input the requested date - another CL argument? 

What do you think? 

Oh and PS: Thank you for writing this tool! I was hoping to find something similar. I think this app only scratched its potential - GUI,  more customizable graphs, you name it (you did, in other issues :) ) and this could be really, really cool.

**Comment by FelixVanOost** [comment]
Good idea, I'll figure out how to add this soon.

Thanks for the kind words! This is really just a fun side project, and like you said there's a lot of potential for improvements based on what people find useful. 👍
